url: http://FPGAwars.github.io
baseurl:

# Site settings
title: Matemáticas 4º ESO
email: rodriguezjasoc@iespedrocerrada.org
description: Dep. de Matemáticas (IES Pedro Cerrada)

# Team names, titles and social links
people:

  - name: Carlos Rodríguez
    social:

      - title: google-plus
        url: https://plus.google.com/u/1/106926421917771551298
      - title: github
        url: https://github.com/crdguez



# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  - content

# Menu
menu:
  - academicas
  - aplicadas
  - miscelanea
